language: node_js
cache:
  directories:
    - node_modules
deploy:
  provider: npm
  email: me@nickdmartin.com
  api_key: $NPM_TOKEN
  on:
    tags: true
  skip_cleanup: true
notifications:
  email:
    on_success: never
    on_failure: always

